#!/usr/bin/bash

trap 'err 130 interrupt' HUP INT QUIT TERM

typeset -g PROGRAM='j'
typeset -g AUTHOR='Nico Pareigis'
typeset -g VERSION='0.1.1'

typeset -A CFG=(
  [cache]="${XDG_CACHE_HOME:-~/.cache}"
  [src]='j_src'
  [dst]='j_dst'
  [ifs]="$IFS"

  [inv]="$PWD"
  [cwd]="$PWD"
  [depth]=8
  [fuzzy]="${J_FUZZY:-fzf}"
  [hidden]=
  [links]=
)

# ---------------------------------------------------------------------- utility

function err {
  printf '%s: %s\n' "$PROGRAM" "$2" 1>&2
  (( $1 > 0 )) && exit $1
}

function dep {
  typeset -a unmet

  for dep in "$@"; do
    if ! command -v $dep 1>/dev/null; then
      unmet+=($dep)
    fi
  done

  local IFS=','
  ((${#unmet[@]} > 0)) && err 4 "dependency not met: ${unmet[*]}"
}

function valid {
  [[ -n $1 && $1 != -- ]]
}

function usage {
  while read; do
    printf "$REPLY\n"
  done <<-EOF
	NAME
	    $PROGRAM - find and jump to child-directories

	SYNOPSIS
	    $PROGRAM [<options>] [<pattern>]
	    $PROGRAM [<options>] [<directory>] [<pattern>...]

	DESCRIPTION
	    $PROGRAM uses \`fd\` to find jump candidates.
	    <directory> specifies the directory in which to search for candidates.
	    <pattern> may be any regex understood by \`fd\` (uses smart-case by
	    default).

	    In case there is more than on jump candidate, the target is determined
	    using a fuzzy finder (see OPTIONS and ENVIRONMENT VARIABLES below). Jump
	    information is cached to allow repeated jumping to specific targets.

	OPTIONS
	    -a | --all
	        Include hidden directories in search results.

	    -d | --depth <int>
	        Set \`fd\` search depth to <int>, default is 8.
	        <int> should be a positive, non-zero integer.

	    -f | --zf
	        Use \`zf\` for fuzzy-finding.

	    -h | --help
	        Print help information and exit.

	    -l | --links
	        Include symlinks in search results.

	    -s | --source
	        Jump to the source directory of the last invocation (i.e. PWD $PROGRAM
	        as last called from).

	    -t | --target
	        Jump to the target of the last invocation.

	    -v | --version
	        Print version information and exit.

	    -y | --fzy
	        Use \`fzy\` for fuzzy-finding.

	    -z | --fzf
	        Use \`fzf\` for fuzzy-finding.

	        \`fzf\`'s multi-selection feature is not properly supported.
	        Usage may result in unexpected behaviour.

	ENVIRONMENT VARIABLES
	    J_FUZZY
	        Can be used to specify a fuzzy-finder program other than the natively
	        supported ones.

	        The program needs to be executable and
	          a) be available in PATH, or
	          b) specified as an absolute or relative path.

	        It should read the jump candidates as a newline separated list from
	        STDIN and return a single line, which will be used as the jump target.

	    J_IGNORE
	        Can be a colon-separated list (similar to PATH) of glob-patterns to
	        exclude from search results (passed to \`fd\`'s '-E' option).

	    J_INVERT_ALL
	        If this is defined and has a value of '1', inverts the behaviour of
	        the -a flag, i.e. includes hidden files in results *unless* -a is
	        present.

	EXIT STATUS
	      1, on argument error
	      2, when no matches are found / missing jump information
	      4, on dependency or filesystem error
	    130, on keyboard interrupt

	DEPENDENCIES
	    Coreutils:
	        realpath

	    Other:
	        fd
	        fzf | fzy | zf (optional, depending on arguments / environment)

	VERSION
	    $VERSION

	AUTHOR(S)
	    $AUTHOR
	EOF
  exit 0
}

function version {
  printf "$PROGRAM $VERSION $AUTHOR\n"
  exit 0
}

# ------------------------------------------------------------------------- func

function parse_cmdline {
  typeset -n n_patterns=$1
  shift

  while [[ -n $@ ]]; do
    case "$1" in
      -a|--all)
        CFG[hidden]='-H'
        shift
        ;;

      -d|--depth)
        typeset arg=$1
        shift

        valid "$1" || err 1 "illegal argument $arg: $1"
        [[ $1 =~ ^[[:digit:]]+$ ]] && (( $1 > 0 )) || err 1 "$arg: expected positive integer, got $arg"

        CFG[depth]=$1
        shift
        ;;

      -f|--zf)
        CFG[fuzzy]='zf'
        shift
        ;;

      -h|--help)
        usage;;

      -l|--links)
        CFG[links]='-L'
        shift
        ;;

      -s|--source)
        rejump ${CFG[src]}
        break
        ;;

      -t|--target)
        rejump ${CFG[dst]}
        break
        ;;

      -v|--version)
        version;;

      -y|--fzy)
        CFG[fuzzy]='fzy'
        shift
        ;;

      -z|--fzf)
        CFG[fuzzy]='fzf'
        shift
        ;;

      -*)
        [[ $1 != -- ]] && err 1 "illegal argument: $1";&

      --|*)
        [[ $1 == -- ]] && shift

        if (( $# > 1 )); then
          [[ ! -d $1 ]] && err 1 "not a directory: $1"

          CFG[cwd]=`realpath "$1"`
          shift
        fi

        patterns+=("$@")
        break
        ;;
    esac
  done
}

function jump {
  typeset -i cache=$1
  typeset target=$2

  if (( $cache == 1 )); then
    printf "${CFG[inv]}\n" 1>"${CFG[cache]}/${CFG[src]}" \
      || err 0 'failed to cache source'
    printf "%s\n" `realpath ${target#/${CFG[cwd]}}` 1>"${CFG[cache]}/${CFG[dst]}" \
      || err 0 'failed to cache destination'

    printf "cd '%s/%s'\n" "${CFG[cwd]%/}" "${target#${CFG[cwd]}}"
    exit 0
  fi

  printf "cd '%s'\n" "$target"
  exit 0
}

function rejump {
  [[ ! -f ${CFG[cache]}/$1 ]] && err 1 'jump cache miss'
  [[ ! -r ${CFG[cache]}/$1 ]] && err 4 'failed to read jump cache'

  jump 0 `< "${CFG[cache]}/$1"`
}

# -------------------------------------------------------------------- execution

typeset -a patterns=()
typeset -a candidates=()
typeset target=

[[ -d ${CFG[cache]} ]] \
  || mkdir "${CFG[cache]}" \
  || err 4 'could not create cache directory'

parse_cmdline patterns "$@"
dep 'fd' 'mkdir' 'realpath' ${CFG[fuzzy]%% *}

cd "${CFG[cwd]}"

mapfile -d$'\n' < <(
  IFS='|' fd \
  -d${CFG[depth]} \
  -td \
  ${CFG[hidden]} \
  ${CFG[links]} \
  "${exclude[@]}" \
  -- "${patterns[*]}"
)

(( ${#MAPFILE[@]} == 0 )) && err 2 'no matches found'

if (( ${#MAPFILE[@]} == 1 )); then
  target="${MAPFILE[0]}"
else
  target=`printf "%s\n" ${MAPFILE[@]} | ${CFG[fuzzy]}`
  [[ -z $target ]] && err 130 'interrupt'
fi

jump 1 "$target"
