#!/usr/bin/perl
use strict;
use warnings;

open(FH, '<', '/sys/class/power_supply/BAT0/status') or die("$!");
  $_ = <FH>;
close(FH) or die("$!");
my $Status;
$Status = '+' if /^Charging\n$/;
$Status = '-' if /^Discharging\n$/;
$Status = '#' if /^Full\n$/;

open(FH, '<', '/sys/class/power_supply/BAT0/capacity') or die("$!");
  my $Capacity = <FH>;
close(FH) or die("$!");
chomp($Capacity);

my $Urgency;
if ($Capacity <= 15) {
  $Urgency = 'critical';
} elsif ($Capacity <= 30) {
  $Urgency = 'normal';
} else {
  $Urgency = 'low';
}

system("dunstify -u $Urgency -h string:x-dunst-stack-tag:batWarn 'Battery: $Capacity% ($Status)'")
  == 0 or die("$!");

