#!/usr/bin/perl
use v5.40;

use Term::ANSIColor qw(colored);
use List::MoreUtils qw(firstidx);

use constant CLR => { i => 'cyan', w => 'yellow', e => 'red' };

# TODO:
# + nvme support
# + multi-mount
# + (un-)mount prevention for system disks

sub err : prototype($$;$) ( $code, $msg, $ctx ) {
    printf( "ud2: %s%s\n", $msg, $ctx ? ": $ctx" : '' );
    exit($code) if $code > 0;
}

sub log : prototype($$) ( $color, $msg ) {
    printf( "%s %s\n", colored( '::', 'bold', CLR->{$color} ), $msg );
}

sub with_file : prototype($&) ( $file, $sub ) {
    open( my $FH, '<', $file )
      || err( 2, 'failed to open file', colored( $file, 'bold' ) );
    my $retval = $sub->($FH);
    close($FH) || err( 2, 'failed to close file', colored( $file, 'bold' ) );

    return $retval;
}

sub with_dir : prototype($&) ( $dir, $sub ) {
    opendir( my $DH, $dir )
      || err( 2, 'failed to open directory', colored( $dir, 'bold' ) );
    my $retval = $sub->($DH);
    closedir($DH)
      || err( 2, 'failed to close directory', colored( $dir, 'bold' ) );

    return $retval;
}

sub in_path : prototype($) ($bin) {
    for ( split( ':', $ENV{PATH} // '' ) ) {
        chop        if m{/$};
        return true if -x "$_/$bin";
    }

    return false;
}

sub dep : prototype(@) (@cmds) {
    if ( my @missing = grep( !in_path($_), @cmds ) ) {
        @missing = map( colored( $_, 'bold' ), @missing );
        err( 4, 'dependency not met', join( ', ', @missing ) );
    }
}

# ------------------------------------------------------------------------------

sub get_newest_dev : prototype() () {
    my $base = '/dev/disk/by-id';

    my @ids = with_dir(
        $base,
        sub : prototype($) ($dh) {
            return [ grep( !( /^(\.|dm-)/ || /-part\d+$/ ), readdir($dh) ) ];
        },
    )->@*;

    err( 2, 'failed to retrieve default device' ) if !@ids;

    my ( $mtime, $dev ) = ( 0, '' );
    foreach (@ids) {
        if ( $mtime < ( stat("$base/$_") )[9] ) {
            $mtime = ( stat(_) )[9];
            $dev   = ( split( '/', readlink("$base/$_") ) )[-1];
        }
    }

    return $dev;
}

sub get_dev_info : prototype($) ($name) {
    chomp( my @stdout = `udisksctl info -b /dev/$name 2>&1` );
    err( 1, 'info fatal', colored( "@stdout", CLR->{e} ) ) if $? > 0;

    chomp(
        my @part = @stdout[
          firstidx( sub { /\bPartitions:/ }, @stdout )
          .. firstidx( sub { /\bType:/ }, @stdout ) - 1
        ]
    );

    return {
        dev       => $name,
        is_crypto => scalar( grep( /\bIdUsage:\s+crypto$/,    @stdout ) ) > 0,
        has_fs    => scalar( grep( /\bIdUsage:\s+filesystem/, @stdout ) ) > 0,
        part      => [ sort( map( s{^.+(\d)$}{$1}r, @part ) ) ],
    };
}

sub get_dm_map : prototype($) ($dev) {
    $dev =~ s/(\d+)$//;
    my $dir = sprintf( "/sys/block/$dev/%sholders", $1 ? "$dev$1/" : '' );

    return (
        with_dir(
            $dir,
            sub : prototype($) ($dh) {
                return [ grep( !/^\./, readdir($dh) ) ];
            },
        )
    )->[0];
}

sub get_dm_mapped_name : prototype($) ($dev) {
    my $f = "/sys/block/$dev/dm/name";
    return $dev if !-e $f;

    return with_file(
        $f,
        sub : prototype($) ($fh) {
            chomp( my $name = "mapper/${\<$fh>}" );
            return $name;
        },
    );
}

sub is_locked : prototype($) ($crypt) {
    return length( get_dm_map($crypt) // '' ) == 0;
}

sub is_mounted : prototype($) ($dev) {
    my $name = get_dm_mapped_name($dev);

    my $mnt = with_file(
        '/proc/mounts',
        sub : prototype($) ($fh) {
            return scalar( grep( m{^/dev/$name\s}, <$fh> ) );
        },
    );

    return $mnt > 0;
}

sub try_unlock : prototype($) ($crypt) {
    &log( 'w', "unlocking ${\colored($crypt, 'bold')}" );

    chomp( $_ = `udisksctl unlock -b /dev/$crypt 2>&1` );
    s/^.+?: GDBus\.Error:.+?: //;
    err( 1, 'unlock fatal', colored( $_, CLR->{e} ) ) if $? > 0;

    &log(
        'w',
"mapped ${\colored($crypt, 'bold')} as ${\colored(get_dm_map($crypt), 'bold')}",
    );
}

sub try_mount : prototype($) ($dev) {
    &log( 'i', "mounting ${\colored( $dev, 'bold' )}" );

    chomp( $_ = `udisksctl mount -b /dev/$dev --no-user-interaction 2>&1` );
    s/^.+?: GDBus\.Error:.+?: //;
    err( 1, 'mount fatal', colored( $_, CLR->{e} ) ) if $? > 0;

    m{Mounted /dev/$dev at (.+)$};
    &log( 'i', "${\colored($dev, 'bold')} mounted at ${\colored($1, 'bold')}",
    );
}

sub try_unmount : prototype($) ($dev) {
    &log( 'i', "unmounting ${\colored($dev, 'bold')}" );

    chomp( $_ = `udisksctl unmount -b /dev/$dev --no-user-interaction 2>&1` );
    s/^.+?: GDBus\.Error:.+?: //;
    err( 1, 'unmount fatal', colored( $_, CLR->{e} ) ) if $? > 0;
}

# ------------------------------------------------------------------------------

dep('udisksctl');
err( 1, 'too many arguments' ) if scalar(@ARGV) > 1;

my $d      = get_dev_info( @ARGV ? shift =~ s{^/dev/}{}r : get_newest_dev() );
my $target = $d->{dev};

err( 1, 'not found', colored( $d->{dev}, 'bold' ) )
  if !-e "/dev/$d->{dev}";
err( 1, 'not a block device', colored( $d->{dev}, 'bold' ) )
  if !-b "/dev/$d->{dev}";

if ( !( $d->{has_fs} || $d->{is_crypto} ) ) {
    err( 1, 'not mountable', colored( $d->{dev}, 'bold' ) )
      if !scalar( @{ $d->{part} } );

    # Fall back to partition with the lowest index.
    $d = get_dev_info( $d->{dev} . $d->{part}->[0] );

    &log(
        'w',
"${\colored($target, 'bold')} does not contain a filesystem, using ${\colored($d->{dev}, 'bold')} instead",
    );
}

# Handle standard mount.
if ( !$d->{is_crypto} ) {
    is_mounted( $d->{dev} )
      ? try_unmount( $d->{dev} )
      : try_mount( $d->{dev} );
    exit(0);
}

# Decrypt and handle LUKS devices.
my $mapped = 0;
is_locked( $d->{dev} ) ? try_unlock( $d->{dev} ) : ( $mapped = 1 );

$d = get_dev_info( get_dm_map( $d->{dev} ) );

&log(
    'w',
    "${\colored($target, 'bold')} is mapped as ${\colored($d->{dev}, 'bold')}",
) if $mapped;

is_mounted( $d->{dev} )
  ? try_unmount( $d->{dev} )
  : try_mount( $d->{dev} );
