#!/bin/sh
# NAME
#   bl - set monitor brightness with brightnessctl
# SYNOPSIS:
#   /path/to/script u|d|s 0-100
#   u -> up, d -> down, s -> set brightness value in percent
# DEPENDENCIES
#   brightnessctl

i=; Inc=${2:-10}; Bctl='brightnessctl -q'
case $1 in
  d) i=0;;
  u) i=1;;
  s) i=2;;
esac

[ -z $i ] && { $Bctl s 30%; exit; }
[ $i -eq 0 ] && { $Bctl s $Inc-%; exit; }
[ $i -eq 1 ] && { $Bctl s +$Inc%; exit; }
[ $i -eq 2 ] && { $Bctl s $Inc%; exit; }
