#!/bin/sh
# NAME
#   lof - launch (if not running) or focus application (if running)
# SYNOPSIS
#   /path/to/script <application name>
# DEPENDENCIES
#   grep, pgrep, wmctrl

Program="$1"
Process=$(pgrep "$Program")

[ $Process ] && [ "$Program" = "gimp" ] && Program="GNU Image Manipulation Program"

if [ -z $Process ]; then
  "$Program"
else
   Wid=$(wmctrl -l | grep -i "$Program")
   Wid=${Wid% *}
   wmctrl -ia "$Wid"
fi
